name: Elm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 13
        uses: actions/setup-node@v3
        with:
          node-version: 13
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm ci
      - run: ./node_modules/.bin/elm make --output /dev/null
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 13
        uses: actions/setup-node@v3
        with:
          node-version: 13
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm ci
      - run: ./node_modules/.bin/elm make --output /dev/null
      - name: elm-format
        run: npx --no-install elm-format --validate

  validate-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 13
        uses: actions/setup-node@v3
        with:
          node-version: 13
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm ci
      - run: ./node_modules/.bin/elm make --output /dev/null
      - name: Build elm docs
        run: ./node_modules/.bin/elm make --docs docs.json

  publish:
    needs: [test, lint, validate-package]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 13
        uses: actions/setup-node@v3
        with:
          node-version: 13
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm ci
      - run: ./node_modules/.bin/elm make --output /dev/null
      - name: Elm Publish
        uses: dillonkearns/elm-publish-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-elm: ./node_modules/.bin/elm
