name: Elm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm install
      - run: ./node_modules/.bin/elm make --output /dev/null
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm install
      - run: ./node_modules/.bin/elm make --output /dev/null
      - name: elm-format
        run: npx --no-install elm-format --validate

  validate-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/cache@v3
        id: elm-cache
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}
      - run: npm install
      - run: ./node_modules/.bin/elm make --output /dev/null
      - name: Build elm docs
        run: ./node_modules/.bin/elm make --docs docs.json
